apiVersion: v2
name: dc-config
description: helm chart for deploying the dc-config service
version: "0.1.0"
dependencies:
  - name: lib-chart
    version: "0.1.0"
    repository: file://../lib-chart

