name: dc-config

replicaCount: 1
#image: krms-dev.kaonrms.com:10443/krms3.1-onp-etv/devicecore/dc-config
image: localhost:32000/nginx
tag: latest
containerPort: 5100
env:
  # Profile
  - name: PROFILE.deployment
    value: ""
  # Main Server
  - name: APP_NAME
    value: "dc-config"
  - name: APP_HOST
    value: "localhost"
  - name: APP_PORT
    value: "5100"
  - name: POOL_SIZE
    value: "1000"
  # Logger
  - name: DEBUG_LEVEL
    value: "TRACE"
  - name: LOG_DISPLAY_STYLE
    value: "CONSOLE"
  # Target Server
  - name: TARGET_SERVICE_NAME1
    value: "df-root"
  - name: TARGET_HOST_NAME1
    value: "df-root"
  - name: TARGET_GRPC_PORT1
    value: "9000"
  # Gcp Config
  #- name: JSON_FILE
  #  value: ""
  #- name: GOOGLE_APPLICATION_CREDENTIALS
  #  value: "/var/secrets/google/prd-dev-key.json"
  # MQ Push, Pull Queue
  - name: PUSH_QUEUE
    value: "task-report"
  - name: PULL_QUEUE
    value: "dc-config-topic"
resources:
  requests:
    cpu: "10m"
    memory: "100Mi"
  limits:
    cpu: "50m"
    memory: "400Mi"
readinessProbe:
  tcpSocket:
    port: 5100
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  tcpSocket:
    port: 5100
  initialDelaySeconds: 15
  periodSeconds: 20

service:
  ports:
  - protocol: TCP
    port: 5200
    targetPort: 5200
  type: NodePort

