FROM node:16-alpine

# We are specifying that the USER which will execute RUN, CMD, or ENTRYPOINT
# instructions will be the node user, as opposed to root (default).
USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

# copy to /app
COPY --chown=node:node package.json .

RUN npm install

# copy all files to /app
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]
