
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: v3.1
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: {{ .Values.name}}
        version: v3.1
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - name: grpc
          containerPort: {{ .Values.deployment.containerPort }}

        env:
        {{- range .Values.deployment.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: backing-services
          - configMapRef:
             name: project-info
        resources:
          requests:
            cpu: {{ .Values. | quote }}
            memory: {{ .Values. | quote }}
          limits:
            cpu: {{ .Values. | quote }}
            memory: {{ .Values. | quote }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values. }}
          initialDelaySeconds: {{ .Values. }}
          periodSeconds: {{ .Values. }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values. }}
          initialDelaySeconds: {{ .Values. }}
          periodSeconds: {{ .Values. }}

