{{- define "lib-chart.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: krms
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  {{- range .Values.service.ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  type: {{ .Values.service.type }}

{{- end -}}
