{{- define "lib-chart.vs" -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: krms
spec:
  hosts:
  {{- range $index, $element := .Values.vs.hosts }}
    {{ $element }}
  {{- end }}
  gateways:
  {{- range $index, $element := .Values.vs.gateways }}
    {{ $element }}
  {{- end }}
  tcp:
  - match:
    - port: {{ .Values.vs.tcp.match.port }}
    route:
    - destination:
        host: {{ .Values.vs.tcp.route.destination "host" }}
        port:
          number: {{ index .Values.vs.tcp.route.destination.port "number" }}
{{- end -}}
