{{- define "lib-chart.vs" -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: krms
spec:
  hosts:
  - {{ .Values.vs.hosts }}
  gateways:
  - {{ .Values.vs.gateways }}
  tcp:
  - match:
    - port: {{ .Values.vs.tcp.match.port }}
    route:
    - destination:
        host: {{ .Values.vs.tcp.route.destination.host }}
        port:
          number: {{ .Values.vs.tcp.route.destination.port.number }}
{{- end -}}
