# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent
#
# version: '3.1'
# services:
  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8111:8111"
    volumes:
      - '$TEAMCITY_HOME/data_dir:/data/teamcity_server/datadir'
      - '$TEAMCITY_HOME/teamcity-server-logs:/opt/teamcity/logs'
    user: "root"
    shm_size: '128m'

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    volumes:
      - '$TEAMCITY_HOME/agents/agent-1/conf:/data/teamcity_agent/conf
    user: "root"
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=$TEAMCITY_SERVER_URL
    shm_size: '256m'



