apiVersion: networking.istio.o/v1alpha3
kind: VirtualService
metadata:
  name: dc-root
  namespace: krms
spec:
  hosts:
  - "etv-dev-dc-root.krms.kaonmedia.com"
  gateways:
  - krms-gateway-tcp-nlb
  tcp:
  - match:
    - port: 5000
    route:
    - destination:
        host: dc-root
        port:
          number: 5000

