apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: v3.1
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: {{ .Values.name}}
        version: v3.1
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image }}:latest
        ports:
        - name: grpc
          containerPort: {{ .Values.deployment.containerPort }}
        env:
        {{- range .Values.deployment.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
        {{- end }}
        #envFrom:
        #  - configMapRef:
        #      name: backing-services
        #  - configMapRef:
        #     name: project-info
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu | quote }}
            memory: {{ .Values.deployment.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu | quote }}
            memory: {{ .Values.deployment.resources.limits.memory | quote }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.deployment.readinessProbe.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.deployment.livenessProbe.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}

