apiVersion: v2
name: parent-chart
version: "0.1.0"
type: application
description: helm chart for dc service
maintainer:
- email: junho.lee@kaongroup.com
  name: junho.lee

dependencies:
  - name: lib-chart
    version: "0.1.0"
    repository: file://../lib-chart
  - name: dc-root
    version: "0.1.0"
    repository: file://../dc-root
  - name: dc-config
    version: "0.1.0"
    repository: file://../dc-config
  - name: dc-control
    version: "0.1.0"
    repository: file://../dc-control
  - name: dc-event
    version: "0.1.0"
    repository: file://../dc-event
