name: dc-event

replicaCount: 1
#image: 088356671508.dkr.ecr.ap-northeast-2.amazonaws.com/krms3.1-aws-etv/devicecore/dc-event:latest
image: localhost:32000/nginx
tag: latest
containerPort: 5300
env:
  # Profile
  - name: PROFILE
    value: ""
  # Main Server
  - name: APP_NAME
    value: "dc-event"
  - name: APP_HOST
    value: "localhost"
  - name: APP_PORT
    value: "5300"
  - name: POOL_SIZE
    value: "1000"
  # Logger
  - name: DEBUG_LEVEL
    value: "TRACE"
  - name: LOG_DISPLAY_STYLE
    value: "CONSOLE"
  # Gcp Config
  #- name: JSON_FILE
  #  value: ""
  #- name: GOOGLE_APPLICATION_CREDENTIALS
  #  value: "/var/secrets/google/prd-dev-key.json"
  - name: PUSH_QUEUE
    value: "dc-event-notify-topic"
  - name: PULL_QUEUE
    value: "df-cwmp-parser-to-dc-event"
envFrom:
  - configMapRef:
      name: backing-services
  - configMapRef:
      name: project-info
resources:
  requests:
    cpu: "10m"
    memory: "100Mi"
  limits:
    cpu: "50m"
    memory: "150Mi"
readinessProbe:
  tcpSocket:
    port: 5300
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  tcpSocket:
    port: 5300
  initialDelaySeconds: 15
  periodSeconds: 20

service:
  ports:
  - protocol: TCP
    port: 5300
    targetPort: 5300
  type: NodePort
